# conda env create --file environment.yml
# conda activate cbb_predict_default

name: {{ cookiecutter.project_slug }}
channels: 
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pyprojroot=0.3.0
  - ipykernel=6.29.4
  - pytz=2024.1
  - pip-chill=1.0.3
  - pyodbc=5.1.0
  - python-dotenv=1.0.1
  - pandas=2.2.2
  - openpyxl=3.1.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - mlflow=2.11.3
  {% if cookiecutter.project_packages == "All" -%}
  - lazypredict=0.2.12
  - tensorflow=2.16.1
  - keras=3.2.1
  - dvc=3.49.0
  - dvc-azure=3.1.0
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
      {% if cookiecutter.project_packages == "All" -%}
      - pyhere
      {% endif -%}